/*
 * Pequeñño programa en Java que permite que
 * Te puedas declarar con tu crush
 * No hay mas, (MIT License)
 */
package View;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LwnaDev
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public FMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSub = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jPuntos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Declararte by LwnaDev");
        setBackground(new java.awt.Color(255, 51, 102));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSi.setBackground(new java.awt.Color(51, 255, 51));
        btnSi.setFont(new java.awt.Font("Bernadette", 1, 14)); // NOI18N
        btnSi.setForeground(new java.awt.Color(255, 255, 255));
        btnSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corazon.png"))); // NOI18N
        btnSi.setText("SI");
        btnSi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        btnSi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        jPanel1.add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, 40));

        btnNo.setBackground(new java.awt.Color(255, 51, 51));
        btnNo.setFont(new java.awt.Font("Bernadette", 1, 14)); // NOI18N
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/roto.png"))); // NOI18N
        btnNo.setText("NO");
        btnNo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        btnNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoMouseEntered(evt);
            }
        });
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 90, 40));

        jPanel3.setBackground(new java.awt.Color(255, 51, 102));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 550, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 550, 260));

        jSub.setBackground(new java.awt.Color(255, 51, 102));

        jTitulo.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("¿ Quieres ser mi otra mitad ?");
        jTitulo.setToolTipText("");
        jSub.add(jTitulo);

        jPuntos.setFont(new java.awt.Font("Bernadette", 0, 14)); // NOI18N
        jPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jPuntos.setText("...");
        jSub.add(jPuntos);

        getContentPane().add(jSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x(){
        Random r=new Random();
        int n=r.nextInt(441);
        return n;
    }
    
    int y(){
        Random r=new Random();
        int n=r.nextInt(191);
        return n;
    }
    
    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        btnNo.setBounds(x(), y(), 90, 40);
        JOptionPane.showMessageDialog(this, "Segui intentando :3");
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseEntered
        btnNo.setBounds(x(), y(), 90, 40);
    }//GEN-LAST:event_btnNoMouseEntered

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        JOptionPane.showMessageDialog(this, "Sabia que dirias que si \n Te quiero muchiissiimo <3");
    }//GEN-LAST:event_btnSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPuntos;
    private javax.swing.JPanel jSub;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
